In [1]:
print('hello world, these are python lab exercises')

hello world, these are python lab exercises


In [7]:
"""
# python introduction
- data types
- variables and constants
"""

# int and str
number = 1
print(number, type(number))
print(str(number), type(str(number)))

# str
name = 'mark'
print(name, type(name))

# float
volume = 3.55
print(volume, type(volume))

# boolean and str
is_student = True
print(is_student, type(is_student), type(str(is_student)))

1 <class 'int'>
1 <class 'str'>
mark <class 'str'>
3.55 <class 'float'>
True <class 'bool'> <class 'str'>


In [32]:
"""
python basics
- loops: for, while
- function
- conditionals: if-else, match-case
- input and output

"""

def is_prime(n):
    prime = True
    if n == 1:
        prime = False
    else:
        for i in range(1, n+1):
            if (i != 1 and i != n) and (n % i == 0):
                prime = False
                break
    return prime


def pattern(line_number):
    n = 1
    for i in range(1, line_number+1):
        counter = 0
        print(end="\n")
        while True:
            if counter == i:
                break
            else:
                if is_prime(n) == True:
                    counter+=1
                    print(f'{n} ', end='')
            n+=1

def main():
    lines = int(input("Enter the number of lines: "))
    pattern(lines)

main()




2 
3 5 
7 11 13 

In [36]:
# list program: create, append, remove

# this is the algorithm for prime numbers

def is_prime(n):
    prime = True
    if n == 1: prime = False
    else:
        for i in range(1, n+1):
            if (i != 1 and i != n) and (n % i == 0):
                prime = False
                break
    return prime

# use list to store prime numbers between 1 and 20 then programmatically remove 2 and 5
prime_numbers = [] # or list([])
for i in range(1, 21):
    if is_prime(i) == True: prime_numbers.append(i)

print(f'prime numbers: {prime_numbers}')
prime_numbers.remove(2)
prime_numbers.remove(5)
print(f'prime numbers: {prime_numbers}')



prime numbers: [2, 3, 5, 7, 11, 13, 17, 19]
prime numbers: [3, 7, 11, 13, 17, 19]


In [68]:
# dictionaries, strings, tuple, set

# 1. dictionarie
student = {'name': 'Mark', 'number': 2, 'university': 'Integral University'} # or dict({})
print(student)
print(list(student.keys()), list(student.values()))
for i, j in student.items():
    print(f"{i}: {j}")

student.setdefault('age', 5)
student['name'] = 'Mark Carrington'
print(student)
print(student.get('course', 0))

# 2. strings
name = 'Elon Musk'
print(type(name)) # type
for char in name:
    print(char, end=' ')
print(f'\nu: {name.index('u')}')
print(list(name), name.split())
print(name.upper(), name.lower(), name.capitalize())

# 3. tuple
person = ('Mark', 14, 'India')
print(f"""
name: {person[0]}
age: {person[1]}
country: {person[2]}
""")
print(list(person))


# 4. sets
fruits = set(['apple', 'banana', 'pineapple', 'pickles', 'banana'])
print(fruits)
fruits.add('pear')
fruits.remove('banana')
print(fruits)


{'name': 'Mark', 'number': 2, 'university': 'Integral University'}
['name', 'number', 'university'] ['Mark', 2, 'Integral University']
name: Mark
number: 2
university: Integral University
{'name': 'Mark Carrington', 'number': 2, 'university': 'Integral University', 'age': 5}
0
<class 'str'>
E l o n   M u s k 
u: 6
['E', 'l', 'o', 'n', ' ', 'M', 'u', 's', 'k'] ['Elon', 'Musk']
ELON MUSK elon musk Elon musk

name: Mark
age: 14
country: India

['Mark', 14, 'India']
{'pickles', 'apple', 'banana', 'pineapple'}
{'pineapple', 'apple', 'pickles', 'pear'}


In [73]:
# the factorial function
def factorial_n(n):
    if n == 0: return 1
    else:
        return n * factorial_n(n-1)
    
def main():
    n = int(input("Number: "))
    print(f"The factorial of {n} is {factorial_n(n)}")

main()

The factorial of 4 is 24


In [82]:
# OOP in python
class Person:
    def __init__(self, name, age, address):
        self.name = name
        self.age = age
        self.address = address
    def __str__(self):
        return str({
            'name': self.name,
            'age': self.age,
            'address': self.address
        })

class Student(Person):
    def __init__(self, name, age, address, enrollment_id, course):
        super().__init__(name, age, address)
        self.enrollment_id = enrollment_id
        self.course = course

    def presentation(self):
        print(f"I am {self.name} from {self.course}, with id: {self.enrollment_id}")

    def __str__(self):
        return str({
            'name': self.name,
            'age': self.age,
            'enrollment_id': self.enrollment_id,
            'course': self.course
        })


sample_student = Student('Mark', 15, 'Lucknow India', '555353', 'Electrical engineering')
print(sample_student)
sample_student.presentation()

    

{'name': 'Mark', 'age': 15, 'enrollment_id': '555353', 'course': 'Electrical engineering'}
I am Mark from Electrical engineering, with id: 555353


In [10]:
pip install ET

Note: you may need to restart the kernel to use updated packages.


In [ ]:
# working with csv, xml, and json files
import csv # working with csv files
import xml.etree.ElementTree as ET # working with xml files
import json

# 1. csv files
with open('datapoint/sample_data.csv', mode="r") as file:
    csv_data = csv.reader(file)
    for row in csv_data:
        print(row)

with open('datapoint/output.csv', mode='w', newline='') as file:
    csv_file = csv.writer(file)
    csv_file.writerow(['Mark', '15', 'mark@example.com'])


# 2. xml files
# accessing xml data
tree = ET.parse('datapoint/sample_data.xml')
root = tree.getroot()

for element in root.findall('.//employee'):
    print(f"{element.find('name').text} {element.find('age').text} {element.find('department').text} {element.find('email').text}")


# creating xml structure
new_root = ET.Element('employees')
employee = ET.SubElement(new_root, 'employee')
ET.SubElement(employee, 'name').text = 'Mark'
ET.SubElement(employee, 'age').text = 16
ET.SubElement(employee, 'department').text = 'Electrical Engineering'
ET.SubElement(employee, 'email').text = 'mark@example.com'
new_tree = ET.ElementTree(new_root)
tree.write('datapoint/output.xml', encoding='utf-8', xml_declaration=True)

# 3. Working with json
with open('datapoint/sample_data.json', 'r') as file:
    print(json.load(file))

new_data = {
    'id': 'mark242',
    'name': 'mark',
    'age': 16,
    'department': 'Electrical Engineering',
    'email': 'mark@example.com'
}

with open('datapoint/output.json', 'w') as file:
    json.dump(new_data, file, indent=4)



['Name', 'Age', 'City', 'Email']
['Alice Johnson', '30', 'New York', 'alice.johnson@example.com']
['Bob Smith', '25', 'Los Angeles', 'bob.smith@example.com']
['Charlie Brown', '35', 'Chicago', 'charlie.brown@example.com']
['Daisy Miller', '28', 'Houston', 'daisy.miller@example.com']
['Evan Davis', '40', 'San Francisco', 'evan.davis@example.com']
['Fiona Clark', '22', 'Seattle', 'fiona.clark@example.com']
['George Lee', '29', 'Miami', 'george.lee@example.com']
['Hannah White', '33', 'Boston', 'hannah.white@example.com']
['Ian Green', '27', 'Dallas', 'ian.green@example.com']
['Jane Wilson', '31', 'Denver', 'jane.wilson@example.com']
Alice Johnson 30 Engineering alice.johnson@example.com
Bob Smith 25 Marketing bob.smith@example.com
Charlie Brown 35 Human Resources charlie.brown@example.com
Daisy Miller 28 Sales daisy.miller@example.com
Evan Davis 40 Finance evan.davis@example.com
{'employees': [{'id': 1, 'name': 'Alice Johnson', 'age': 30, 'department': 'Engineering', 'email': 'alice.john

In [24]:
# working with numpy
import numpy as np
data = np.loadtxt('datapoint/test_set.csv', delimiter=',', skiprows=1)
print(data)

# numpy mathematical functions
data1 = [1, 2, 3]
data2 = [2, 4, 6]
print(np.add(data1, data2))
print(np.subtract(data1, data2))
print(np.multiply(data1, data2))
print(np.divide(data1, data2))

[[ 1.  10.5 20.3]
 [ 2.  15.7 25.4]
 [ 3.  12.9 22.8]]
[3 6 9]
[-1 -2 -3]
[ 2  8 18]
[0.5 0.5 0.5]


In [ ]:
# working with metasploit
